# Generated by Django 5.2.7 on 2025-11-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_tag_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Author',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='edited',
        ),
        migrations.RemoveField(
            model_name='post',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(choices=[('travel', 'Travel'), ('science', 'Science'), ('history', 'History'), ('math', 'Math'), ('beauty', 'Beauty'), ('cars', 'Cars'), ('technology', 'Technology'), ('entertainment', 'Entertainment'), ('hollywood', 'Hollywood'), ('news', 'News'), ('sports', 'Sports')], max_length=30, unique=True),
        ),
    ]
