# Generated by Django 5.2.7 on 2025-11-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0005_remove_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default='Untitled'),
            preserve_default=False,
        ),
    ]
